name: Nuget Package Deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.404'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100' 

    - name: Build
      run:  dotnet build -c Release
      
    - name: Test
      run:  dotnet test /p:CollectCoverage=true /p:CoverletOutput=../CoverageResults/ /p:CoverletOutputFormat=Cobertura

    - name: Codecov install
      run: dotnet tool install --global Codecov.Tool
      
    - name: Push to codecov net5
      run: codecov -f CoverageResults/coverage.net5.0.cobertura.xml -t ${{ secrets.CODECOV_TOKEN }} 
      
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: pack
      run: dotnet pack -c Release
    - name: push
      run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_DEPLOY_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

