name: Nuget Package Deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
    
    - name: Build
      run:  dotnet build -c Release
    
    - name: Test
      run:  dotnet test

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pack
      run: dotnet pack -c Release
    - name: push
      run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_DEPLOY_KEY }} -s https://api.nuget.org/v3/index.json  

